package com.go.asap;

public class P22Table {


    public final static String TABLES = "PBV1_B0C_B0F_B0G\n" +
            "FAM_1PP2_AFFEC_B0P\n" +
            "FAM_1PP2_B0H_D2A\n" +
            "FAM_1PP2_B0M_B0N\n" +
            "FAM_1PP2_B0P_B0R\n" +
            "FAM_1PP2_D25\n" +
            "FAM_1PP2_D6E_REG\n" +
            "FAM_1PP2_DAA\n" +
            "FAM_1PP2_DAB\n" +
            "FAM_1PP2_DAL\n" +
            "FAM_1PP2_DAO\n" +
            "FAM_1PP2_DAQ\n" +
            "FAM_1PP2_DBB\n" +
            "FAM_1PP2_DBJ\n" +
            "FAM_1PP2_DCB\n" +
            "FAM_1PP2_DCF\n" +
            "FAM_1PP2_DCF_DCG\n" +
            "FAM_1PP2_DCG\n" +
            "FAM_1PP2_DCX\n" +
            "FAM_1PP2_DDA\n" +
            "FAM_1PP2_DE3\n" +
            "FAM_1PP2_DE3_DZJ\n" +
            "FAM_1PP2_DEE\n" +
            "FAM_1PP2_DFH\n" +
            "FAM_1PP2_DFH_B0F\n" +
            "FAM_1PP2_DFH_DNK\n" +
            "FAM_1PP2_DFX\n" +
            "FAM_1PP2_DGG\n" +
            "FAM_1PP2_DGM_DZJ\n" +
            "FAM_1PP2_DGQ\n" +
            "FAM_1PP2_DGQ_B0P\n" +
            "FAM_1PP2_DGV\n" +
            "FAM_1PP2_DHG\n" +
            "FAM_1PP2_DI4_REG\n" +
            "FAM_1PP2_DI8_REG\n" +
            "FAM_1PP2_DI9_REG\n" +
            "FAM_1PP2_DIM\n" +
            "FAM_1PP2_DIN\n" +
            "FAM_1PP2_DIP_DRH\n" +
            "FAM_1PP2_DJA\n" +
            "FAM_1PP2_DJB\n" +
            "FAM_1PP2_DJB_B0G\n" +
            "FAM_1PP2_DJB_DZJ\n" +
            "FAM_1PP2_DJD\n" +
            "FAM_1PP2_DJD_B0N\n" +
            "FAM_1PP2_DK9\n" +
            "FAM_1PP2_DLA\n" +
            "FAM_1PP2_DLE\n" +
            "FAM_1PP2_DLT\n" +
            "FAM_1PP2_DLU_DLT\n" +
            "FAM_1PP2_DLZ_\n" +
            "FAM_1PP2_DMG\n" +
            "FAM_1PP2_DMT\n" +
            "FAM_1PP2_DMZ\n" +
            "FAM_1PP2_DN8_DJB\n" +
            "FAM_1PP2_DNA\n" +
            "FAM_1PP2_DNA_B0P\n" +
            "FAM_1PP2_DNA_DRH\n" +
            "FAM_1PP2_DNF\n" +
            "FAM_1PP2_DNG\n" +
            "FAM_1PP2_DNK\n" +
            "FAM_1PP2_DNM\n" +
            "FAM_1PP2_DO1\n" +
            "FAM_1PP2_DO2\n" +
            "FAM_1PP2_DOK\n" +
            "FAM_1PP2_DOR\n" +
            "FAM_1PP2_DPD\n" +
            "FAM_1PP2_DPX_B0D\n" +
            "FAM_1PP2_DRE\n" +
            "FAM_1PP2_DRE_DWV\n" +
            "FAM_1PP2_DRE_DZJ\n" +
            "FAM_1PP2_DRJ\n" +
            "FAM_1PP2_DRJ_DRK\n" +
            "FAM_1PP2_DRJ_LT_YI\n" +
            "FAM_1PP2_DRL\n" +
            "FAM_1PP2_DRL_DLE\n" +
            "FAM_1PP2_DRU\n" +
            "FAM_1PP2_DRZ\n" +
            "FAM_1PP2_DSB\n" +
            "FAM_1PP2_DSD\n" +
            "FAM_1PP2_DSP\n" +
            "FAM_1PP2_DUH\n" +
            "FAM_1PP2_DUN_D6F\n" +
            "FAM_1PP2_DVB\n" +
            "FAM_1PP2_DVD\n" +
            "FAM_1PP2_DVD_B0F\n" +
            "FAM_1PP2_DVF_DLW\n" +
            "FAM_1PP2_DVH\n" +
            "FAM_1PP2_DVQ\n" +
            "FAM_1PP2_DWV_AFFEC\n" +
            "FAM_1PP2_DWV_B0F\n" +
            "FAM_1PP2_DWV_DZV\n" +
            "FAM_1PP2_DWY_AFFEC\n" +
            "FAM_1PP2_DWY_DZJ\n" +
            "FAM_1PP2_DYD\n" +
            "FAM_1PP2_DYD_DFH\n" +
            "FAM_1PP2_DYD_DGM\n" +
            "FAM_1PP2_DYE_\n" +
            "FAM_1PP2_DYI\n" +
            "FAM_1PP2_DYR\n" +
            "FAM_1PP2_DYR_DIM\n" +
            "FAM_1PP2_DZH\n" +
            "FAM_1PP2_DZH_AFFEC\n" +
            "FAM_1PP2_DZJ_AFFEC\n" +
            "FAM_1PP2_DZJ_DI2\n" +
            "FAM_1PP2_DZV_AFFEC\n" +
            "FAM_1PP2_DZV_DFH\n" +
            "FAM_1PP2_D_E_F_G_H\n" +
            "FAM_1PP2_PACK_DWV\n" +
            "PK_1PP2_DWY_02\n" +
            "PK_1PP2_DZJ_01\n" +
            "PK_1PP2_DZV_01";


}
