package com.go.asap;


public class ZZK9Table {

    public final static String TABLES = "FAM_ZZK9_B0B_DUF\n" +
            "FAM_ZZK9_B0G_DRG\n" +
            "FAM_ZZK9_B0M_B0N\n" +
            "FAM_ZZK9_B0N_B0E\n" +
            "FAM_ZZK9_B0N_B0P\n" +
            "FAM_ZZK9_B0P_B0E\n" +
            "FAM_ZZK9_BDEFJ\n" +
            "FAM_ZZK9_D0N\n" +
            "FAM_ZZK9_D25_B0D\n" +
            "FAM_ZZK9_D48\n" +
            "FAM_ZZK9_DAB\n" +
            "FAM_ZZK9_DAL\n" +
            "FAM_ZZK9_DAN\n" +
            "FAM_ZZK9_DAN_DPC\n" +
            "FAM_ZZK9_DAN_DZH\n" +
            "FAM_ZZK9_DAO\n" +
            "FAM_ZZK9_DAO_DUX\n" +
            "FAM_ZZK9_DAQ\n" +
            "FAM_ZZK9_DAS\n" +
            "FAM_ZZK9_DAX\n" +
            "FAM_ZZK9_DBJ\n" +
            "FAM_ZZK9_DBO\n" +
            "FAM_ZZK9_DBQ\n" +
            "FAM_ZZK9_DBV\n" +
            "FAM_ZZK9_DCA\n" +
            "FAM_ZZK9_DCB\n" +
            "FAM_ZZK9_DCO\n" +
            "FAM_ZZK9_DCP\n" +
            "FAM_ZZK9_DCR\n" +
            "FAM_ZZK9_DCX\n" +
            "FAM_ZZK9_DCZ\n" +
            "FAM_ZZK9_DD3\n" +
            "FAM_ZZK9_DD4\n" +
            "FAM_ZZK9_DD4_DLI\n" +
            "FAM_ZZK9_DDA\n" +
            "FAM_ZZK9_DDK\n" +
            "FAM_ZZK9_DDY\n" +
            "FAM_ZZK9_DDZ\n" +
            "FAM_ZZK9_DDZ_B0F\n" +
            "FAM_ZZK9_DDZ_DGA\n" +
            "FAM_ZZK9_DE3\n" +
            "FAM_ZZK9_DE8\n" +
            "FAM_ZZK9_DE8_DGM\n" +
            "FAM_ZZK9_DED_DDZ\n" +
            "FAM_ZZK9_DEJ\n" +
            "FAM_ZZK9_DEN_DER\n" +
            "FAM_ZZK9_DER_DCU\n" +
            "FAM_ZZK9_DES\n" +
            "FAM_ZZK9_DFC\n" +
            "FAM_ZZK9_DFE\n" +
            "FAM_ZZK9_DFGHJ_DKA\n" +
            "FAM_ZZK9_DFH\n" +
            "FAM_ZZK9_DFX\n" +
            "FAM_ZZK9_DGB\n" +
            "FAM_ZZK9_DGM\n" +
            "FAM_ZZK9_DGM_DYB\n" +
            "FAM_ZZK9_DGQ\n" +
            "FAM_ZZK9_DHU\n" +
            "FAM_ZZK9_DHU_DGM\n" +
            "FAM_ZZK9_DHY\n" +
            "FAM_ZZK9_DI3\n" +
            "FAM_ZZK9_DI3_DRG\n" +
            "FAM_ZZK9_DI8_9_DZJ\n" +
            "FAM_ZZK9_DI8_DI9\n" +
            "FAM_ZZK9_DIQ\n" +
            "FAM_ZZK9_DIT\n" +
            "FAM_ZZK9_DJO\n" +
            "FAM_ZZK9_DJU\n" +
            "FAM_ZZK9_DJY\n" +
            "FAM_ZZK9_DK6\n" +
            "FAM_ZZK9_DK6_B0H\n" +
            "FAM_ZZK9_DK6_DUE\n" +
            "FAM_ZZK9_DKG\n" +
            "FAM_ZZK9_DLE\n" +
            "FAM_ZZK9_DLI\n" +
            "FAM_ZZK9_DLI_UB_GM\n" +
            "FAM_ZZK9_DLK\n" +
            "FAM_ZZK9_DLV_DAN\n" +
            "FAM_ZZK9_DLW\n" +
            "FAM_ZZK9_DLW_DI3\n" +
            "FAM_ZZK9_DLW_DNB\n" +
            "FAM_ZZK9_DMG\n" +
            "FAM_ZZK9_DMP\n" +
            "FAM_ZZK9_DN2\n" +
            "FAM_ZZK9_DNA\n" +
            "FAM_ZZK9_DNB_DHG\n" +
            "FAM_ZZK9_DNB_DPR\n" +
            "FAM_ZZK9_DNF\n" +
            "FAM_ZZK9_DNL\n" +
            "FAM_ZZK9_DNM\n" +
            "FAM_ZZK9_DO2\n" +
            "FAM_ZZK9_DOR\n" +
            "FAM_ZZK9_DOU\n" +
            "FAM_ZZK9_DOV\n" +
            "FAM_ZZK9_DPB_PC_VG\n" +
            "FAM_ZZK9_DPD_DED\n" +
            "FAM_ZZK9_DPQ\n" +
            "FAM_ZZK9_DPR\n" +
            "FAM_ZZK9_DPX\n" +
            "FAM_ZZK9_DQF\n" +
            "FAM_ZZK9_DQK\n" +
            "FAM_ZZK9_DRB\n" +
            "FAM_ZZK9_DRB_DZJ\n" +
            "FAM_ZZK9_DRB_RE_CU\n" +
            "FAM_ZZK9_DRE\n" +
            "FAM_ZZK9_DRG\n" +
            "FAM_ZZK9_DRG_DGM\n" +
            "FAM_ZZK9_DRL\n" +
            "FAM_ZZK9_DRS\n" +
            "FAM_ZZK9_DRU\n" +
            "FAM_ZZK9_DSD\n" +
            "FAM_ZZK9_DUB\n" +
            "FAM_ZZK9_DUD\n" +
            "FAM_ZZK9_DUE\n" +
            "FAM_ZZK9_DUF\n" +
            "FAM_ZZK9_DUH\n" +
            "FAM_ZZK9_DVC\n" +
            "FAM_ZZK9_DVD_DLE\n" +
            "FAM_ZZK9_DVH\n" +
            "FAM_ZZK9_DVI\n" +
            "FAM_ZZK9_DVT\n" +
            "FAM_ZZK9_DWL_B0E\n" +
            "FAM_ZZK9_DWL_B0H\n" +
            "FAM_ZZK9_DXN\n" +
            "FAM_ZZK9_DXY\n" +
            "FAM_ZZK9_DYD\n" +
            "FAM_ZZK9_DYD_DHG\n" +
            "FAM_ZZK9_DYQ\n" +
            "FAM_ZZK9_DYR\n" +
            "FAM_ZZK9_DYR_DJO\n" +
            "FAM_ZZK9_DZH_DUF\n" +
            "FAM_ZZK9_DZJ_B0E\n" +
            "FAM_ZZK9_FH_AQ_BQ\n" +
            "FAM_ZZK9_P_AN_AL\n" +
            "FAM_ZZK9_QK_PB\n" +
            "FAM_ZZK9__DLZ\n" +
            "FAM_ZZK9__DOF\n" +
            "FAM_K9V7_PACK_DZJ\n" +
            "FAM_K9V7_PACK_DZV\n" +
            "FAM_ZZK9V7_B0H_D2A";

}
